### ISSUE TITLE
in provider "pks": An argument named "target" is not expected here.

### ISSUE THREAD

**Issue by t-settle** [benjvi/terraform-provider-pks#1]
Ben, first thanks so much for developing a PKS provider. I have been looking for one and am pushing VMware to provide one too. I pulled yours down today and installed it, but was seeing the following issue. Any ideas why it says that?

Error: Unsupported argument
 on pks.tf line 3, in provider "pks":
   3:   target = 10.1.1.14
An argument named "target" is not expected here.

Details:
[root@mehost]# terraform -v
Terraform v0.12.18
+ provider.pks (unversioned)
[root@mehost]# terraform plan
Error: Unsupported argument

  on pks.tf line 3, in provider "pks":
   3:   target = 10.1.1.14

An argument named "target" is not expected here.
[root@mehost]# cat pks.tf
provider "pks" {
  target = 10.1.1.14
  client_id = "$PKS_CLIENT_ID"
  client_secret = "$PKS_CLIENT_SECRET"
  skip_ssl_validation = true
}

resource "pks_cluster" "thomastest" {
  name = "thomastest1"
  external_hostname = "thomastest1-api.example.com"
  plan = "small"
  num_nodes = 3
}

**Comment by benjvi** [comment]
Hey @t-settle , thanks!

Looks like I have some mistakes in the docs and in the examples too. I'll update them
The correct field should be "hostname" instead of "target"

Does it work for you with that change?

**Comment by t-settle** [comment]
Yep that was it. Works perfectly now, thanks!
